version: "3.8"

services:
  #nginx:
   # build: 
    #  context: ./nginx
    #container_name: "nginx_cont"
    #ports:
      #- "81:80"
    #restart: always
    #depends_on:
    #  - flask_app
    #networks:
     # - notes-app-nw

  flask_app:
    build: 
      context: .
    container_name: "flask_cont"
    ports:
      - "5000:5000"
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
